Refreshtoken feature new
zaitOlzhas/CryptoBank pull request #3
Opened 2024-12-01 10:20 UTC by zaitOlzhas

2024-12-03 04:43 UTC, mitro requested changes

2024-12-03 04:43 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Requests/Authenticate.cs
> +            await mediator.Send(request, cancellationToken);
The refresh token should not be returned in the response. Instead, it should be set as an HttpOnly cookie. This prevents a client-side code from accessing the refresh token. It is much more secure. The browser will send the refresh token automatically as a cookie. The cookie must also have `Path` set. This will instruct the browser to send the cookie only to the designated paths.

Learn about cookies at https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies.

2024-12-03 04:43 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Requests/RefreshToken.cs
> +            await mediator.Send(request,cancellationToken);
The refresh token should be sent as a cookie. So you should extract it from a cookie here.

2024-12-03 04:43 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Requests/RefreshToken.cs
> +                .FirstOrDefaultAsync(cancellationToken);
It is better to use `SingleOrDefault` when you expect only one item to be returned. This better indicates the semantics.

2024-12-03 04:43 UTC, mitro commented on CryptoBank_WebApi/Database/CryptoBank_DbContext.cs
> +            userRefreshToken.Property(x => x.Token)
You should have an index on this field because you filter tokens based on it.

2024-12-03 04:43 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Common/JwtTokenGenerator.cs
> +    public async Task<UserRefreshToken> GenerateRefreshToken(int userId, CancellationToken cancellationToken)
I propose to separate methods with a blank line

2024-12-03 04:43 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Common/JwtTokenGenerator.cs
> +        using (var rng = RandomNumberGenerator.Create())
Let's use `using var rng = RandomNumberGenerator.Create();` Then you can just write:

```csharp
using var rng = RandomNumberGenerator.Create();
var randomNumber = new byte[32];
rng.GetBytes(randomNumber);
var refreshToken = Convert.ToBase64String(randomNumber);
```

2024-12-03 04:43 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Domain/UserRefreshToken.cs
> +    public int UserId { get; set; }
`set`s should be replaced with `init`s. This will prevent the object modification after it is created.

Let's also use `required` with these three properties to indicate they are not nullable.

2024-12-03 04:43 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Requests/RefreshToken.cs
> +            var principal = jwtTokenGenerator.GetPrincipalFromExpiredToken(request.Token.AccessToken);
You already have a principal in `HttpContext.User`. The authentication middleware sets it. Here, you duplicate the token validation logic, which is not necessary at all.

Extract the principal from `HttpContext` in the endpoint and pass it to the handler inside the request.

2024-12-03 04:43 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Common/JwtTokenGenerator.cs
> +    public async Task<UserRefreshToken> GenerateRefreshToken(int userId, CancellationToken cancellationToken)
The responsibility of `JwtTokenGenerator` is to generate JWT tokens. I would suggest extracting the logic that deals with refresh tokens into a separate class.

2024-12-03 04:43 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Requests/RefreshToken.cs
> +        public override async Task<Response> ExecuteAsync(Request request,CancellationToken cancellationToken) =>
No spaces after the commas

2024-12-16 07:57 UTC, mitro requested changes

2024-12-16 07:57 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Requests/Authenticate.cs
> +            _httpContextAccessor.HttpContext.Response.Cookies.Append("RefreshToken", refreshToken.Token, new CookieOptions
The request handler should not know anything about HTTP-specific things. It can be called from an HTTP endpoint, but tomorrow, it can also be called from a gRPC endpoint or a WebSocket endpoint.

Therefore, it is better to return a JWT and a refresh token from the handler and append the refresh token to the HTTP-specific cookies in the `Endpoint` class. After that, you can remove `IHttpContextAccessor` from `RequestHandler`.

2024-12-16 07:57 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Requests/RefreshToken.cs
> +            var refreshToken = httpContextAccessor.HttpContext.Request.Cookies["RefreshToken"];
Remove `IHttpContextAccessor` from the class dependencies and deal with cookies in the `Endpoint` class as I indicated in the previous comment.

2024-12-16 07:57 UTC, mitro commented on CryptoBank_WebApi/Database/CryptoBank_DbContext.cs
> +            userRefreshToken.HasIndex(x => x.Token);
`userRefreshToken.Property(x => x.Token)` should not be removed since you still should map this property to a DB field.

You should have just added `userRefreshToken.HasIndex(x => x.Token);` on the separate line.

2024-12-16 07:57 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Domain/UserRefreshToken.cs
> +    [Required]
Not `[Required]`, but `public required string Token { get; init;l }`. Learn more at https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required

2024-12-16 07:57 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Requests/RefreshToken.cs
> +            var principal = httpContextAccessor.HttpContext.User;
Get a principal from HttpContext in the `Endpoint` class and pass it inside the `Request` object, as I proposed in my original comment https://github.com/zaitOlzhas/CryptoBank/pull/3#discussion_r1867039043

2024-12-16 07:57 UTC, mitro commented on CryptoBank_WebApi/Features/Auth/Common/TokenGenerator.cs
> +    public ClaimsPrincipal GetPrincipalFromExpiredToken(string token)
This method is not used. You can delete it.

2024-12-16 15:52 UTC, zaitOlzhas commented on CryptoBank_WebApi/Features/Auth/Requests/Authenticate.cs
> +            _httpContextAccessor.HttpContext.Response.Cookies.Append("RefreshToken", refreshToken.Token, new CookieOptions
To seperate Endpoint and Handler created seperate EndpointResponse, cause refresh token will be in http cooke, not in body.

2024-12-16 16:51 UTC, zaitOlzhas commented on CryptoBank_WebApi/Features/Auth/Common/TokenGenerator.cs
> +    public ClaimsPrincipal GetPrincipalFromExpiredToken(string token)
done

2024-12-16 16:51 UTC, zaitOlzhas commented on CryptoBank_WebApi/Features/Auth/Requests/Authenticate.cs
> +            _httpContextAccessor.HttpContext.Response.Cookies.Append("RefreshToken", refreshToken.Token, new CookieOptions
done

2024-12-16 16:51 UTC, zaitOlzhas commented on CryptoBank_WebApi/Features/Auth/Requests/RefreshToken.cs
> +            var refreshToken = httpContextAccessor.HttpContext.Request.Cookies["RefreshToken"];
done

2024-12-16 16:52 UTC, zaitOlzhas commented on CryptoBank_WebApi/Features/Auth/Requests/RefreshToken.cs
> +            var principal = httpContextAccessor.HttpContext.User;
done

2024-12-16 16:53 UTC, zaitOlzhas commented on CryptoBank_WebApi/Database/CryptoBank_DbContext.cs
> +            userRefreshToken.HasIndex(x => x.Token);
done

2024-12-16 16:55 UTC, zaitOlzhas commented on CryptoBank_WebApi/Features/Auth/Domain/UserRefreshToken.cs
> +    [Required]
done

2024-12-17 05:15 UTC, mitro approved these changes

2024-12-17 05:17 UTC, merged