Account feature
zaitOlzhas/CryptoBank pull request #6
Opened 2024-12-22 16:50 UTC by zaitOlzhas

2024-12-25 10:14 UTC, mitro requested changes

2024-12-25 10:14 UTC, mitro commented on CryptoBank_WebApi/Features/Account/Domain/Account.cs
> +
Unnecessary blank line

2024-12-25 10:14 UTC, mitro commented on CryptoBank_WebApi/Features/Account/Requests/CreateAccount.cs
> +            var claims = request.Principal.Claims.ToList();
Why do you create a new list here?

2024-12-25 10:14 UTC, mitro commented on CryptoBank_WebApi/Features/Account/Requests/CreateAccount.cs
> +            if (!request.Principal.HasClaim(x => x.Type == ClaimTypes.Email))
You can delete this check and check `email is not null` after line 39 instead. The code will be simpler

2024-12-25 10:14 UTC, mitro commented on CryptoBank_WebApi/Features/Account/Requests/CreateAccount.cs
> +                .ToListAsync(cancellationToken);
You don't need to get accounts here. You can use `CountAsync`, and the SQL will be `SELECT COUNT(*) ...`. and it will return a single number. This will be faster and consume less memory

2024-12-25 10:14 UTC, mitro commented on CryptoBank_WebApi/Features/Account/Requests/GetUserAccounts.cs
> +            if (!request.Principal.HasClaim(x => x.Type == ClaimTypes.Email))
This check can be simplified as well

2024-12-25 10:14 UTC, mitro commented on CryptoBank_WebApi/Features/Account/Requests/MoneyTransfer.cs
> +            if (!request.Principal.HasClaim(x => x.Type == ClaimTypes.Email))
This same code is written in two more places. I propose to extract it to some helper to reduce duplication

2024-12-25 10:14 UTC, mitro commented on CryptoBank_WebApi/Database/CryptoBank_DbContext.cs
> +            account.Property(x => x.UserId)
Accounts are often looked up based on a UserId. This property should be indexed to make this operation efficient

2024-12-25 10:14 UTC, mitro commented on CryptoBank_WebApi/Database/CryptoBank_DbContext.cs
> +            account.HasIndex(x => x.Number);
Primary keys are indexes by default, so no need to create a separate index

2024-12-25 15:31 UTC, zaitOlzhas commented on CryptoBank_WebApi/Features/Account/Domain/Account.cs
> +
fixed

2024-12-25 15:34 UTC, zaitOlzhas commented on CryptoBank_WebApi/Features/Account/Requests/CreateAccount.cs
> +            var claims = request.Principal.Claims.ToList();
fixed

2024-12-25 15:34 UTC, zaitOlzhas commented on CryptoBank_WebApi/Features/Account/Requests/CreateAccount.cs
> +            if (!request.Principal.HasClaim(x => x.Type == ClaimTypes.Email))
fixed

2024-12-25 15:35 UTC, zaitOlzhas commented on CryptoBank_WebApi/Features/Account/Requests/CreateAccount.cs
> +                .ToListAsync(cancellationToken);
fixed

2024-12-25 15:38 UTC, zaitOlzhas commented on CryptoBank_WebApi/Features/Account/Requests/GetUserAccounts.cs
> +            if (!request.Principal.HasClaim(x => x.Type == ClaimTypes.Email))
fixed

2024-12-25 15:40 UTC, zaitOlzhas commented on CryptoBank_WebApi/Database/CryptoBank_DbContext.cs
> +            account.HasIndex(x => x.Number);
fixed

2024-12-25 15:41 UTC, zaitOlzhas commented on CryptoBank_WebApi/Database/CryptoBank_DbContext.cs
> +            account.Property(x => x.UserId)
fixed

2024-12-26 06:28 UTC, mitro approved these changes

2024-12-26 16:02 UTC, merged